### ISSUE TITLE
Refactor code in websockets.js 

### ISSUE THREAD

**Issue by rochakjain361** [rochakjain361/BugTracker#28]
Refactor Code on Frontend:
https://github.com/rochakjain361/BugTracker/blob/master/frontend/frontend/src/WebSocket.js
1) Remove the unnecessary console.log() s.
2) Refactor code as per js format.
3) Remove other redundant chunks of code.

**Comment by Garg-Doppler** [comment]
I'll be working on this issue. Thanks.
